### ISSUE TITLE
Cookie issues on opera?

### ISSUE THREAD

**Issue by Shingetsu-Kurai** [Ndragomirov/twitch-now#74]
When used on opera (beta, haven't tested with normal), logging in results in twitch logging the user out.
Moreover, after a bit of time (have not measured, may be linked to when user logs back into twitch), extension will require you to log in again.

**Comment by Ndragomirov** [comment]
When used on opera (beta, haven't tested with normal), logging in results in twitch logging the user out.

Twitch Now doesnt edit/modifies cookies

Moreover, after a bit of time (have not measured, may be linked to when user logs back into twitch), extension will require you to log in again.

Sometimes twitch API responses with 401 Unauthorized status on any our request(like updating favorite channels), so Twitch Now deletes ouath token and logouts user instantly (on opera build, on chrome build we just ignore 401 Unauthorized errors because of mad users :smile:   )

**Comment by Shingetsu-Kurai** [comment]
Still, fact is every time I relogin into twitch now, I get logged out from twitch.
If it doesn't modify cookies, maybe after dropping the oauth token it generates a new one and that messes with something?

**Comment by Ndragomirov** [comment]
ok i dug into it. Twitch logouts you if redirect_uri contains dots(?)

please test it on your side

1. this link should logout you from twitch:

https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=b4sj5euottb8mm7pc1lfvi84kvzxqxk&redirect_uri=http%3A%2F%2Fndragomirov.github.io%2Ftwitch.html&scope=user_read

2. this link should Not

https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=se20ps66q66jxacq65tgwr22okwhfur&redirect_uri=http%3A%2F%2Fndragomirov.github.io%2Ftwitch&scope=user_read
